service: meter-reads

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-2
  stage: dev
  profile: dtl-serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-2:*:*"

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: meterReads
          method: post
          cors: true

  search:
    handler: handler.search
    events:
      - http:
          path: meterReads/search
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                meterNumber: false
                readingTime: true

resources:
  Resources:
    MeterReadsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: readingTime
            AttributeType: N
          -
            AttributeName: meterNumber
            AttributeType: S
        KeySchema:
          -
            AttributeName: readingTime
            KeyType: HASH
          -
            AttributeName: meterNumber
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 100
        TableName: 'meter-reads'